### PR TITLE
Hate to be the bearer of bad news

### PR DESCRIPTION
**Pull request by asottile**
`pyupgrade` has no public python api and so it should not be used as a library

it's only intended use is as a commandline utility

(issues aren't enabled so I don't know how else to communicate this)

### CODE REVIEW

**Comment by asottile** [comment]
@verhovsky basically, expect this to break

**Comment by verhovsky** [comment]
@asottile I could w

**Comment by verhovsky** [comment]
Are you opposed to pyupgrade having a public API like black's?

**Comment by asottile** [comment]
yes, the internals change quite often and new settings are added / removed / refactored pretty often

**Comment by verhovsky** [comment]
I hope I'm not being annoying, but I added a public API for formatting strings anyway. 

I could write to a tempfile, run `pyupgrade` on it and read it back, but that wouldn't be pretty and if you ever change the options, I would still end up calling pyupgrade with outdated options, so it's the same as passing an `argparser.Namespace` object to a string formatting function.

I also pinned the minor version in setup.cfg https://github.com/verhovsky/pyupgrade-docs/commit/cea2837e69a913d8153fe3274ff6221467d5e760

**Comment by asottile** [comment]
I'll not change it in patch versions, so that's probably enough?

**Comment by verhovsky** [comment]
Can you maybe accept a `_format_str` so that people know to not use it? I'll read all the changes any time I bump the patch version. It's just copying the if statements from the pyupgrade code is ugly.

Or should I just delete this project? I only made it to upgrade the pytest docs https://github.com/pytest-dev/pytest/commit/75d0b899bbb56d6849e9d69d83a9426ed3f43f8b

**Comment by asottile** [comment]
I think this is fine, just like be aware that it's not supported and you may need to make adjustments

**Pull request closed without merging**
